---
    #######################
    t_start: 0
    t_end: 24
    num_cores: 4
    data_source:
        capacities: online
        costs: online
        initial_demand: online
    openEntrance:
        capacities:
            scenario: "Techno-Friendly 1.0"
            year: 2050
            model: 'GENeSYS-MOD 2.9.0-oe'
            region: 'Denmark'
            variable: 'Capacity|Electricity|*'
        costs:
            scenario: '*'
            year: 2050
            model: '*'
            region: 'Scandinavia'
            variable: 'Variable Cost|Electricity|*'
        initial_demand:
            scenario: '*'
            year: 2050
            model: 'plan4EU v0.1'
            region: 'Scandinavia'
            variable: 'Final Energy|Electricity|Heat'
        sources:
            - 'Biomass'
            - 'Gas'
            - 'Solar'
            - 'Wind|Offshore'
            - 'Wind|Onshore'
        dispatchable_sources:
            - 'Biomass'
            - 'Gas'
        non_dispatchable_sources:
            - 'Solar'
            - 'Wind|Offshore'
            - 'Wind|Onshore'
