user: 'user'
password: 'pass'
outputpath: 'C:\\Users\\F04340\\Documents\\OneDrive - EDF\\OpenEntrance\\WP5\\datasets_IAMC\\'

model: 'GENeSYS-MOD 2.9.0-oe'
years: [2050]
scenarios: ['Directed Transition 1.0']

listvariables: ['Capacity|Electricity|*','Emissions|CO2|Energy|Supply|Electricity']

listregionsScen: ['Austria' , 'Belgium' , 'Bulgaria' , 'Croatia' , 'Czech Republic' , 'Denmark' , 'Estonia' , 'Finland' , 'France' , 'Germany' ,'Greece' , 'Hungary' , 'Ireland' , 'Italy' , 'Latvia' , 'Lithuania' , 'Luxembourg' , 'Non-EU-Balkans' , 'Norway' , 'Poland' , 'Portugal' , 'Romania' , 'Slovakia' , 'Slovenia' , 'Spain' , 'Sweden' , 'Switzerland' , 'The Netherlands' , 'Turkey' ,'United Kingdom']

aggregateregions:
    Baltics: ['Estonia', 'Latvia', 'Lithuania']
    Balkans: ['Non-EU-Balkans', 'Bulgaria', 'Croatia','Greece','Romania','Slovenia']
    Scandinavia: ['Denmark', 'Finland', 'Sweeden','Norway']

listregionsPlan4eu: ['Austria' , 'Belgium' , 'Czech Republic' , 'France' , 'Germany' , 'Hungary' , 'Ireland' , 'Italy' , 
'Hungary', 'Poland' , 'Portugal' , 'Slovakia' , 'Spain' , 'Switzerland' , 'The Netherlands' , 'United Kingdom', 'Balkans', 
'Baltics', 'Scandinavia']

